version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: aws-sdk
    versions:
    - ">= 0"
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: serverless
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
    - 5.24.2
    - 5.24.3
    - 5.25.1
    - 5.27.0
    - 5.27.1
    - 5.30.0
  - dependency-name: lint-staged
    versions:
    - 10.5.4
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.14
    - 7.13.8
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: serverless-iam-roles-per-function
    versions:
    - 3.1.0
  - dependency-name: serverless-plugin-split-stacks
    versions:
    - 1.10.0
    - 1.11.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
    - 8.0.2
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.3.5
  - dependency-name: elliptic
    versions:
    - 6.5.4
